/*       Source:  Backing Store                                                               */
/*     Location:  js/page/editapps.js r110506                                                 */
/*      Machine:  10.16.140.107                                                               */
/*    Generated:  July 17th 2008 4:10:12 AM PDT                                               */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */


var EditAppsController={removeBookmarkedApp:function(appID){var id=$('bookmarked_app_'+appID);EditAppSettings.setup(appID,false).setBookmarked(0,function(){animation(id).to('opacity',0).to('height',0).hide().duration(400).go();DOM.remove(id);});return false;},permissionsCount:{},setPermissionsCount:function(permissionsCount){this.permissionsCount=permissionsCount;},removeExtendedPermission:function(appID,permission){var handler=function(asyncResponse){var tr=$('extperms_app_'+permission+'_'+appID);if(this.permissionsCount[permission]==1){DOM.remove($('extperm_section_banner_'+permission));DOM.remove(tr.parentNode.parentNode);}else{DOM.remove(tr);}
this.permissionsCount[permission]--;};EditAppSettings.setup(appID,false).setExtendedPermission(permission,0,handler.bind(this));},_setupHoverOnPencil:function(link){link.parentNode.onmouseover=function(){CSS.addClass(this,'hover');};link.parentNode.onmouseout=function(){CSS.removeClass(this,'hover');};},initFlyoutMenus:function(appIds){for(var i=0;i<appIds.length;i++){var appId=appIds[i];var menuId='flyout_menu_'+appId;var clickTarget=$('edit_link_'+appId);this._setupHoverOnPencil(clickTarget);new flyout_menu(clickTarget).setPosition(dropmenu.ALIGN_LEFT).registerHTMLMenu(menuId).addHook('show',CSS.addClass.bind(null,clickTarget,'selected_pencil')).addHook('hide',CSS.removeClass.bind(null,clickTarget,'selected_pencil'));}},initProfileTabHovers:function(appIds){for(var i=0;i<appIds.length;i++){this._setupHoverOnPencil($('edit_link_'+appIds[i]));}},initBookmarkedApps:function(appIds){this.sortableGroup=new SortableGroup();this.bookmarkedApps=appIds;this.sortableGroup.setOrderChangeHandler(function(){var newOrder=this.sortableGroup.getOrder();var applications=[];for(var i=0;i<newOrder.length;i++){var index=newOrder[i];applications.push(this.bookmarkedApps[index]);}
EditAppSettings.reorderBookmarks(applications);}.bind(this));for(var i=0;i<appIds.length;i++){var appId=appIds[i];var obj=$('bookmarked_app_'+appId);var handle=$('drag_div_'+appId);this.sortableGroup.addSortable(i,obj,handle);}},showApplicationSettingsDialog:function(appId,visibleTab){show_edit_app_dialog(appId,visibleTab);return false;},removeApplication:function(appId,appName){appName=htmlize(appName);var title=tx('apps:remove-title',{'application-name':appName});var edit_application_link='<a href="/editapps.php">'+tx('apps:remove-edit-link')+'</a>';var content='<p>'+tx('apps:remove-body',{'edit-applications-link':edit_application_link})+'</p>'+'<p><strong>'+tx('apps:remove-prompt',{'application-name':appName})+'</strong></p>'+'<input type="hidden" name="remove_appId" value="'+appId+'" />';var button=tx('apps:remove-button');var removeCallback=function(){var appElem=ge('app_'+appId);if(appElem){DOM.remove(appElem);}}
EditAppSettings.setup(appId,false);new Dialog().setTitle(title).setBody(content).setButtons([{'name':'remove','label':button},Dialog.CANCEL]).setHandler(EditAppSettings.removeApplication.bind(EditAppSettings,appId,removeCallback)).show();return false;},showProfileTab:function(appId){show_edit_app_dialog(appId,'profile');return false;},showFeedTab:function(appId){show_edit_app_dialog(appId,'publishing');},saveAppPrivacy:function(privacyData){EditAppSettings.savePrivacy(privacyData);},saveExternalWebsitePolicy:function(setting,app_id){EditAppSettings.setup(app_id,false,'profile').setExternalWebsitePolicy(setting);return true;},saveGlobalExternalWebsitePolicy:function(setting){EditAppSettings.setGlobalExternalWebsitePolicy(setting);return true;},initFeedTab:function(appFeedPermissions){this.feedPermissions=appFeedPermissions},filterFeed:function(){var select=$('editapps_select_options');var selectedIndex=select.selectedIndex;var selectedValue=select.options[selectedIndex].value;for(var appID in this.feedPermissions){var option=$('feed_apps_'+appID);if(selectedValue==0){show(option);}else if(selectedValue==this.feedPermissions[appID]){show(option);}else{hide(option);}}}}
if(window.Bootloader){Bootloader.done(1);}