/*       Source:  Backing Store                                                               */
/*     Location:  js/edit_app_settings.js r110506                                             */
/*      Machine:  10.16.140.102                                                               */
/*    Generated:  July 17th 2008 4:10:12 AM PDT                                               */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */


function show_edit_app_dialog(app_id,visible_tab){EditAppSettings.setup(app_id,true,visible_tab);}
EditAppSettings={currentTab:undefined,dialogUrl:'/ajax/editapp_dialog.php',callbackUrl:'/ajax/edit_app_settings.php',statusElement:'edit_app_settings_save_fill',appID:0,uiMode:false,setup:function(appID,uiMode,currentTab){this.appID=appID;this.uiMode=uiMode;this.currentTab=currentTab||'profile';if(this.uiMode){this.showDialog();}
return this;},showDialog:function(){var async=new AsyncRequest().setURI(this.dialogUrl).setData({'app_id':this.appID,'visible_tab':this.currentTab});new Dialog().setAsync(async).setStackable(true).show();return this;},switchTab:function(tabName){CSS.removeClass(this.currentTab+'_tab_link','tab_link_selected');hide('app_settings_'+this.currentTab+'_tab');CSS.addClass(tabName+'_tab_link','tab_link_selected');show('app_settings_'+tabName+'_tab');this.currentTab=tabName;},setBookmarked:function(bookmarked,callback){var handler=callback||bagofholding;var async=new AsyncRequest().setURI(this.callbackUrl).setHandler(handler).setData({'bookmark':1,'bookmarked':bookmarked,'app_id':this.appID});if(this.uiMode){async.setStatusElement(this.statusElement);}
async.send();if(this.uiMode){toggleDisplayNone('edit_app_settings_app_bookmarked');toggleDisplayNone('edit_app_settings_app_not_bookmarked');}},setAllowPublish:function(setting){if(setting==2){$('edit_app_settings_allow_publish_small_radio').disabled=true;$('edit_app_settings_allow_publish_medium_radio').disabled=true;$('edit_app_settings_allow_publish_large_radio').disabled=true;$('edit_app_settings_allow_publish_ask_radio').disabled=true;$('edit_app_settings_allow_publish_small_radio').checked=false;$('edit_app_settings_allow_publish_medium_radio').checked=false;$('edit_app_settings_allow_publish_large_radio').checked=false;$('edit_app_settings_allow_publish_ask_radio').checked=false;}else{$('edit_app_settings_allow_publish_small_radio').disabled=false;$('edit_app_settings_allow_publish_medium_radio').disabled=false;$('edit_app_settings_allow_publish_large_radio').disabled=false;$('edit_app_settings_allow_publish_ask_radio').disabled=false;}
new AsyncRequest().setStatusElement(this.statusElement).setURI(this.callbackUrl).setHandler(bagofholding).setData({'publishing':1,'setting':setting,'app_id':this.appID}).send();return true;},setExtendedPermission:function(permission,allow,callback){var handler=callback||bagofholding;var async=new AsyncRequest().setURI(this.callbackUrl).setHandler(handler).setData({'extended':1,'permission':permission,'allow':allow,'app_id':this.appID});if(this.uiMode){async.setStatusElement(this.statusElement);}
async.send();return true;},makeProfileChange:function(item,action){new AsyncRequest().setStatusElement(this.statusElement).setURI(this.callbackUrl).setHandler(bagofholding).setData({'profile':1,'item':item,'action':action,'app_id':this.appID}).send();toggleDisplayNone('app_settings_profile_'+item+'_added');toggleDisplayNone('app_settings_profile_'+item+'_to_add');EditAppSettings.setCurrentlyAdded(this.currentlyAdded+(action=='add'?1:-1));},currentlyAdded:0,setCurrentlyAdded:function(num){this.currentlyAdded=num;if(this.currentlyAdded==3){hide('edit_app_settings_to_add');}else{show('edit_app_settings_to_add');}
if(this.currentlyAdded==0){hide('edit_app_settings_added');}else{show('edit_app_settings_added');}},savePrivacy:function(privacyData){privacyData['privacy']=1;var async=new AsyncRequest().setURI(this.callbackUrl).setHandler(bagofholding).setData(privacyData);if(this.uiMode){async.setStatusElement(this.statusElement);}
async.send();},removeApplication:function(appID,callback){var handler=callback||bagofholding;new AsyncRequest().setURI(this.callbackUrl).setHandler(handler).setData({'remove':1,'app_id':appID}).send();},reorderBookmarks:function(appIDs){new AsyncRequest().setURI(this.callbackUrl).setHandler(bagofholding).setData({'reorder_bookmarks':1,'app_ids':appIDs}).send();},setExternalWebsitePolicy:function(setting){new AsyncRequest().setURI(this.callbackUrl).setHandler(bagofholding).setData({external_site:1,app_id:this.appID,policy:setting}).send();},setGlobalExternalWebsitePolicy:function(setting){new AsyncRequest().setURI(this.callbackUrl).setHandler(bagofholding).setData({global_external_site:1,policy:setting?1:0}).send();}}
if(window.Bootloader){Bootloader.done(1);}