/*       Source:  Global Cache                                                                */
/*     Location:  js/lib/util/quickling.js r110180                                            */
/*      Machine:  10.16.139.102                                                               */
/*    Generated:  July 16th 2008 1:55:16 PM PDT                                               */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */


var HistoryManager={history:null,current:0,fragment:null,nextframe:function(frame){if(frame!==undefined){HistoryManager.iframeQueue.push(frame);}else{HistoryManager.iframeQueue.splice(0,1);HistoryManager.iframeTimeout=null;}
if(HistoryManager.iframeQueue.length&&!HistoryManager.iframeTimeout){var src=HistoryManager.iframeQueue[0];HistoryManager.iframeTimeout=setTimeout(function(){HistoryManager.iframe.src='/common/history_manager.html?|'+src+'#'+src;},100,false);}},init:function(){if(HistoryManager._initialized){return HistoryManager;}
var uri=URI();var cur_fragment=uri.getFragment()||'';copy_properties(HistoryManager,{_initialized:true,fragment:cur_fragment,orig_fragment:cur_fragment,history:[uri],callbacks:[],lastChanged:new Date().getTime(),canonical:URI('#'),fragmentTimeout:null,user:0,iframeTimeout:null,iframeQueue:[],enabled:true,debug:bagofholding});if(ua.safari()<500||ua.firefox()<2){HistoryManager.enabled=false;return HistoryManager;}
if(ua.ie()){HistoryManager.iframe=document.createElement('iframe');copy_properties(HistoryManager.iframe.style,{width:'1px',height:'1px',left:'-10000px',top:'-10000px',position:'absolute'});onloadRegister(function(){HistoryManager.iframe.onload=function(){setInterval(HistoryManager.checkURI,42,false);};HistoryManager.iframe.src='/common/history_manager.html';document.body.insertBefore(HistoryManager.iframe,document.body.firstChild);});}else{setInterval(HistoryManager.checkURI,42,false);if(ua.safari()){HistoryManager.historyOrigin=window.history.length;}}
return HistoryManager;},registerURIHandler:function(callback){HistoryManager.callbacks.push(callback);return HistoryManager;},setCanonicalLocation:function(loc){HistoryManager.canonical=URI(loc);return HistoryManager;},notify:function(uri){if(uri==HistoryManager.orig_fragment){uri=HistoryManager.canonical.getFragment();}
for(var ii=0;ii<HistoryManager.callbacks.length;ii++){try{if(HistoryManager.callbacks[ii](uri)){return true;}}catch(ex){Util.error('Uncaught exception in HistoryManager URI handler callback: %x',ex);}}
return false;},checkURI:function(){if(new Date().getTime()-HistoryManager.lastChanged<400){return;}
if(HistoryManager.iframeQueue.length){return;}
if(ua.safari()&&window.history.length==200){if(!HistoryManager.warned){HistoryManager.warned=true;Util.error('Your history length is over 200 and you are in Safari; things will '+'start behaving oddly now. This is a known bug.');}
return;}
var frag=URI().getFragment();if(ua.safari()){var hpos=window.history.length-HistoryManager.historyOrigin;if(hpos<HistoryManager.history.length&&hpos>=0){frag=HistoryManager.history[hpos].getFragment();}}else if(ua.ie()){frag=URI(HistoryManager.iframe.contentWindow.document.location.href).getFragment();}
if(frag!=HistoryManager.fragment){HistoryManager.debug([frag,' vs ',HistoryManager.fragment,'whl: ',window.history.length,'ho: ',HistoryManager.historyOrigin,'hpos: ',hpos,'QHL: ',HistoryManager.history.length].join(' '));for(var ii=HistoryManager.history.length-1;ii>=0;--ii){if(HistoryManager.history[ii].getFragment()==frag){break;}}
++HistoryManager.user;if(ii>=0){HistoryManager.go(ii-HistoryManager.current);}else{HistoryManager.go('#'+frag);}
--HistoryManager.user;}
delete frag;},go:function(href,now,replace){HistoryManager.debug('go: '+href);if(now===undefined){now=true;}
if(!HistoryManager.enabled){if(!now){return false;}}
if(typeof(href)=='number'){if(!href){return false;}
var dst=href+HistoryManager.current;var loc=Math.max(0,Math.min(HistoryManager.history.length-1,dst));HistoryManager.current=loc;dst=HistoryManager.history[loc].getFragment()||HistoryManager.orig_fragment;HistoryManager.fragment=dst;HistoryManager.lastChanged=new Date().getTime();if(ua.ie()){if(HistoryManager.fragmentTimeout){clearTimeout(HistoryManager.fragmentTimeout);}
HistoryManager.fragmentTimeout=setTimeout(function(){window.location.hash='#'+dst;},750,false);if(!HistoryManager.user){if(replace){Util.error('HistoryManager.go does not support replace mode in IE now.');return false;}
HistoryManager.nextframe(dst);}}else if(!HistoryManager.user){if(replace){window.location.replace(URI().setFragment(dst).toString());}else{window.location.hash='#'+dst;}}
if(now){HistoryManager.notify(dst);}
return false;}
href=URI(href);if(href.getDomain()==URI().getDomain()){href=URI('#'+href.getUnqualifiedURI());}
var cur=HistoryManager.history[HistoryManager.current].getFragment();var tgt=href.getFragment();if(tgt==cur||(cur==HistoryManager.orig_fragment&&tgt==HistoryManager.canonical.getFragment())){if(now){HistoryManager.notify(tgt);}
return false;}
if(replace){HistoryManager.current--;}
var wipe=(HistoryManager.history.length-HistoryManager.current)-1;HistoryManager.history.splice(HistoryManager.current+1,wipe);HistoryManager.history.push(URI(href));return HistoryManager.go(1,now,replace);},getCurrentFragment:function(){var cur_fragment=URI.getRequestURI().getFragment();return cur_fragment==HistoryManager.orig_fragment?HistoryManager.canonical.getFragment():cur_fragment;}};onloadRegister(HistoryManager.init);var Quickling={_scroll_positions:{},_transition_handlers:[],isActive:function(){return Quickling._is_active||false;},init:function(version){var canonical_uri=URI.getRequestURI().getUnqualifiedURI();copy_properties(Quickling,{_is_active:true,_version:version,_current_uri:canonical_uri,_most_recent_uri:canonical_uri});HistoryManager.init().setCanonicalLocation('#'+canonical_uri).registerURIHandler(Quickling._loadPage);LinkController.registerFallbackHandler(Quickling._rewriteHref,LinkController.ALL_TARGETS|LinkController.ALL_KEY_MODIFIERS);LinkController.registerFallbackHandler(Quickling._onlinkclick);FormController.registerFallbackHandler(Quickling._onformsubmit);window.onscroll=chain(window.onscroll,function(){var frag=HistoryManager.getCurrentFragment();if(Quickling._current_uri==frag){Quickling._scroll_positions[frag]=Vector2.getScrollPosition();}});Quickling._instrumentTimeoutFunc('setInterval');Quickling._instrumentTimeoutFunc('setTimeout');Quickling.registerTransitionHandler(Quickling._defaultTransitionHandler);},registerTransitionHandler:function(transition_handler){if(!Quickling._transition_handlers.contains(transition_handler)){Quickling._transition_handlers.push(transition_handler);}},_isPageActive:function(uri){if(uri=='#'){return false;}
var uri=new URI(uri);if(uri.getDomain()&&uri.getDomain()!=URI().getDomain()){return false;}
var regex=Quickling._isPageActive.regex;if(!regex){regex=Quickling._isPageActive.regex=new RegExp(env_get('quickling_inactive_page_regex'));}
if(regex.test(uri.getPath())){return false;}
return true;},_rewriteHref:function(link){var old_href=link.getAttribute('href');var new_href=_computeRelativeURI(Quickling._most_recent_uri.getQualifiedURI(),old_href).toString();if(old_href!=new_href){link.setAttribute('href',new_href);}},_onlinkclick:function(link){_BusyUIManager.lookBusy(link);Quickling.go(link.getAttribute('href'));return false;},go:function(uri,replace){if((replace&&ua.ie())||!Quickling._isPageActive(uri)){if(replace&&!ua.ie()){window.location.replace(uri.toString());}else{window.location.href=uri.toString();}
return;}
var qualified_uri=new URI(uri).getQualifiedURI();var unqualified_uri=qualified_uri.getUnqualifiedURI();delete Quickling._scroll_positions[unqualified_uri];_BusyUIManager.lookBusy();Quickling._loadPage(unqualified_uri);HistoryManager.go(qualified_uri.toString(),false,replace);},_loadPage:function(uri){var uri_s=uri.toString();uri=new URI(uri_s);if(uri_s.charAt(0)!='/'){return false;}
if(uri.getFragment()&&are_equal(URI(uri).setFragment(null),URI(Quickling._current_uri).setFragment(null))){Quickling._current_uri=Quickling._most_recent_uri=uri;Quickling._adjustScrollForCurrentURI();_BusyUIManager.stopLookingBusy();return true;}
Quickling._load_count=(Quickling._load_count||0)+1;if(Quickling._isTimeToRefresh()){Quickling._redirect(uri_s);return false;}
var scroll_position=Quickling._scroll_positions[Quickling._current_uri];Quickling._current_uri=null;if(scroll_position){Vector2.scrollTo(scroll_position);}
var handle_transition=Quickling._handleTransition.bind(null,uri);var beforeleave_warning=_runHooks('onbeforeleavehooks');if(beforeleave_warning){_BusyUIManager.stopLookingBusy();Quickling._warnBeforeLeaving(beforeleave_warning,handle_transition);}else{handle_transition();}
return true;},_handleTransition:function(uri){window.onbeforeleavehooks=undefined;_BusyUIManager.lookBusy();for(var i=Quickling._transition_handlers.length-1;i>=0;--i){if(Quickling._transition_handlers[i](uri)===true){return;}else{Quickling._transition_handlers.splice(i,1);}}
Util.error('No transition handler returned true.  This should be '
+'impossible, since _defaultTransitionHandler always returns true, '
+'and it gets registered in Quickling.init.');},_defaultTransitionHandler:function(uri){uri=new URI(uri).addQueryData({quickling:true});new AsyncRequest().setURI(uri.getPath()).setData(uri.getQueryData()).setHandler(Quickling._onpagedata).setFinallyHandler(Quickling.transitionComplete).setMethod('GET').setReadOnly(true).setOption('useIframeTransport',true).send();return true;},_onpagedata:function(response){var payload=response.getPayload();Quickling._current_uri=Quickling._most_recent_uri=new URI(HistoryManager.getCurrentFragment());if(payload.redirect){Quickling.go(payload.redirect,true);return;}
document.title=payload.title||'Facebook';if(payload.version!=Quickling._version){Quickling._redirect(payload.uri);return;}
_runHooks('onleavehooks');var content_div=ge('content');if(content_div){content_div.style.height='1234px';content_div.innerHTML='';}
Vector2.scrollTo(new Vector2(0,0,'document'));var body_class=payload.body_class||'';document.body.className=body_class
+(CSS.hasClass(document.body,'chat_body')?' chat_body':'');var page_body_element=ge('page_body');if(page_body_element){page_body_element.className=body_class+' pagebody';}
for(var div_id in payload.content){var div=ge(div_id);if(div){set_inner_html(div,payload.content[div_id],true);}else{Util.warn('Unknown content div id: '+div_id);}}
if(content_div&&content_div.style.height=='1234px'){content_div.style.height='';}
Quickling._adjustScrollForCurrentURI.defer();},transitionComplete:function(){_BusyUIManager.stopLookingBusy();},_warnBeforeLeaving:function(warning_text,continuation){new Dialog().setTitle(tx('ql:leave-warn-title')).setSummary(tx('ql:leave-warn-body',{ok:tx('sh:ok-button'),cancel:tx('sh:cancel-button')})).setBody(htmlize(warning_text)).setButtons(Dialog.OK_AND_CANCEL).setHandler(continuation).setModal().show();},_isTimeToRefresh:function(){return Quickling._load_count>=10;},_redirect:function(uri){uri=new URI(uri).removeQueryData('quickling').toString();if(window.location.href==uri){window.location.reload();}else{window.location.replace(uri);}},_instrumentTimeoutFunc:function(original_name){window[original_name+'_native']=(function(orig){var _native=function _native(func,delay){return orig(func,delay);};return _native;})(window[original_name]);window[original_name]=function _setTimeout(func,delay,clear_on_quickling_event){var timeout_id=window[original_name+'_native'](func,delay);if(delay>0){onunloadRegister(function(){clearInterval(timeout_id);},clear_on_quickling_event);}
return timeout_id;};},_adjustScrollForCurrentURI:function(){var current_uri=Quickling._current_uri;var anchor=Quickling._getAnchor(current_uri.getFragment());if(anchor){var anchor_position=Vector2.getElementPosition(anchor);anchor_position.x=0;Vector2.scrollTo(anchor_position);return;}
var scroll_position=Quickling._scroll_positions[current_uri];if(scroll_position){Vector2.scrollTo(scroll_position);}},_getAnchor:function(name){if(!name){return null;}
var anchors=$$('a');for(var i=0,l=anchors.length;i<l;++i){if(anchors[i].name==name){return anchors[i];}}
return ge(name);},_onformsubmit:function(form){var old_action=new URI(form.getAttribute('action')||'');var new_action=_computeRelativeURI(Quickling._most_recent_uri,old_action);form.setAttribute('action',new_action.toString());var method=form.method?form.method.toUpperCase():'GET';if(method=='GET'){Quickling.go(new_action.addQueryData(serialize_form(form)));return false;}else{}}};function _computeRelativeURI(original,delta){var ret=new URI(),delta_=delta;original=new URI(original);delta=new URI(delta);if(!delta.isFacebookURI()){return delta_;}
var source=original;var components=['Protocol','Domain','Port','Path','QueryData','Fragment'];components.forEach(function(component){var combine_paths=component=='Path'&&source===original;if(combine_paths){ret.setPath(_computeRelativePath(original.getPath(),delta.getPath()));}
if(!is_empty(delta['get'+component]())){source=delta;}
if(!combine_paths){ret['set'+component](source['get'+component]());}});return ret;}
function _computeRelativePath(original,delta){if(!delta){return original;}
if(delta.charAt(0)=='/'){return delta;}
var parts=original.split('/').slice(0,-1);if(parts[0]!==''){Util.warn('Original path is not absolute.');}
delta.split('/').forEach(function(part){if(part=='.'){}else if(part=='..'){if(parts.length>1){parts=parts.slice(0,-1);}}else{parts.push(part);}});return parts.join('/');}
var _BusyUIManager={_looking_busy:false,_original_cursors:[],lookBusy:function(link_element){if(link_element){_BusyUIManager._giveProgressCursor(link_element);}
if(_BusyUIManager._looking_busy){return;}
_BusyUIManager._looking_busy=true;_BusyUIManager._giveProgressCursor(document.body);},stopLookingBusy:function(){if(!_BusyUIManager._looking_busy){return;}
_BusyUIManager._looking_busy=false;while(_BusyUIManager._original_cursors.length){var element_and_cursor=_BusyUIManager._original_cursors.pop();var element=element_and_cursor[0];var cursor=element_and_cursor[1];if(element.style){element.style.cursor=cursor||'';}}},_giveProgressCursor:function(element){_BusyUIManager._original_cursors.push([element,element.style.cursor]);element.style.cursor='progress';}};
if(window.Bootloader){Bootloader.done(1);}