/*       Source:  Backing Store                                                               */
/*     Location:  js/scrollarea.js r109048                                                    */
/*      Machine:  10.16.139.106                                                               */
/*    Generated:  July 15th 2008 12:34:51 AM PDT                                              */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */


function ScrollArea(scroll_div_id,content_div_id,down_arrow_id,up_arrow_id){if(this===window){Util.error('You\'re doing this wrong.  This is a class and should be '+'with new ScrollArea(...);');return;}
copy_properties(this,{scroll_div:$(scroll_div_id),content_div:$(content_div_id),down_arrow:$(down_arrow_id),up_arrow:$(up_arrow_id)});copy_properties(this,{auto_move_interval:null,allow_page_scroll:true,max_height:false});this.down_arrow.onmouseout=bind(this,'_endAutoMove');this.down_arrow.onmouseover=bind(this,'_startAutoMove',ScrollArea.HOVER_INTERVAL,ScrollArea.DOWN);this.up_arrow.onmouseout=bind(this,'_endAutoMove');this.up_arrow.onmouseover=bind(this,'_startAutoMove',ScrollArea.HOVER_INTERVAL,ScrollArea.UP);this.scroll_div.onmouseover=bind(this,'_disallowPageScroll');this.scroll_div.onmouseout=bind(this,'_allowPageScroll');ScrollWheel.addHandler(this._pageScrollResponse.bind(this));ScrollArea.instances.push(this);this.update();}
copy_properties(ScrollArea,{HOVER_INTERVAL:50,MOUSE_WHEEL_MULTIPLE:-8,UP:1,DOWN:2,instances:[],getInnerInstance:function(element){for(var i=0;i<ScrollArea.instances.length;i++){if(is_descendent(ScrollArea.instances[i].scroll_div,element)){return ScrollArea.instances[i];}}
return false;}});copy_properties(ScrollArea.prototype,{_startAutoMove:function(interval_time,direction){var move_fn=bind(this,this.moveBy,(direction==ScrollArea.UP)?-11:11);this.auto_move_interval=setInterval(move_fn,interval_time);},_endAutoMove:function(){clearInterval(this.auto_move_interval);},_disallowPageScroll:function(){this.allow_page_scroll=false;},_allowPageScroll:function(){this.allow_page_scroll=true;},_pageScrollResponse:function(delta){if(!this.allow_page_scroll){var round_fn=delta>0?Math.ceil:Math.floor
this.moveBy(ScrollArea.MOUSE_WHEEL_MULTIPLE*round_fn(delta));}
return this.allow_page_scroll;},_scrollTop:function(){return(-1*parseInt(this.content_div.style.marginTop))||0;},_setScrollTop:function(new_top){new_top=this._enforceRange(new_top);this.content_div.style.marginTop=-new_top+'px';},_isAtTop:function(){return this._scrollTop()==0;},_isAtBottom:function(){var scrollTop=this._scrollTop();return scrollTop==this._enforceRange(scrollTop+1);},_enforceRange:function(test_val){var new_top;var hidden_content_height=Vector2.getElementDimensions(this.content_div).y-
Vector2.getElementDimensions(this.scroll_div).y;if(test_val<0){new_top=0;}else if(test_val>hidden_content_height){new_top=hidden_content_height;}else{new_top=test_val;}
return new_top;},setMaxHeight:function(new_max){this.max_height=new_max;},moveBy:function(distance){var current_top=this._scrollTop();var new_top=current_top+distance;this._setScrollTop(new_top);this.update();},moveTo:function(destination){this._setScrollTop(destination);this.update();},update:function(){var content_size=Vector2.getElementDimensions(this.content_div);var scroll_size=Vector2.getElementDimensions(this.scroll_div);if(content_size.y){if(content_size.y>=this.max_height&&scroll_size.y!=this.max_height){this.scroll_div.style.height=this.max_height+'px';}else if(content_size.y<this.max_height&&scroll_size.y!=content_size.y){this.scroll_div.style.height=content_size.y+'px';}}
this._isAtTop()?CSS.addClass(this.scroll_div,'at_top'):CSS.removeClass(this.scroll_div,'at_top');this._isAtBottom()?CSS.addClass(this.scroll_div,'at_bottom'):CSS.removeClass(this.scroll_div,'at_bottom');}});ScrollWheel=function(){var _listenerAttached=false;var _callbacks=[];var _handle=function(event){var delta=0;event=event_get(event);if(event.wheelDelta){delta=event.wheelDelta/120;if(ua.opera()){delta=-delta;}}else if(event.detail){delta=-event.detail/3;}
if(delta){for(var i=0;i<_callbacks.length;i++){if(!_callbacks[i](delta)){event_kill(event);return;}}}};return{addHandler:function(callback){if(!_listenerAttached){if(window.addEventListener){window.addEventListener('DOMMouseScroll',_handle,false);}
window.onmousewheel=document.onmousewheel=_handle;_listenerAttached=true;}
_callbacks.push(callback);}};}();
if(window.Bootloader){Bootloader.done(1);}